apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: app-message
  namespace: flux-system
spec:
  interval: 1m  # Check for changes every minute
  url: https://github.com/mayankraipure11/gitops.git # The repository URL
  secretRef:
    name: my-git-auth
  ref:
    branch: main